### ISSUE TITLE
Going to the Deep Dark crashes the server

### ISSUE THREAD

**Issue by Nincodedo** [Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen#176]
http://pastebin.com/mgir0cYq

**Comment by Nincodedo** [comment]
Findings so far: Poor Ores don't like the Deep Dark. Possibly due to lack of stone and abundance of cobble. Blacklisting Poor Ores from the Deep Dark fixes this issue however there may be another way to fix this.

**Comment by UndeadZeratul** [comment]
After more testing and tweaking, it seems it's the CoFH fractal generation that's to blame.  I've gone ahead and refactored our generation json files to better represent their intent, which is to define what ores generate in different dimensions, rather than from what mods.  This also helps break out differences in generations due to differences in dimensions, such as sea level changes or block composition.

After refactoring the files, having only deep iron and osmium generate in the deep dark, that dimension now loads fine.  I'll continue to refine the generation in that dimension and hopefully we'll have something comprehensive, without the cost of performance.
