### ISSUE TITLE
Many Minetweaker errors

### ISSUE THREAD

**Issue by Nincodedo** [Nincraft/NincraftElectricBoogaloo2RevengeoftheFallen#217]
http://pastebin.com/1qRNRaNz

**Comment by Nincodedo** [comment]
After commenting out the gas conduit changes, these errors still exist. Mostly AOBD changes.

http://pastebin.com/9mMAks9t

**Comment by UndeadZeratul** [comment]
ModTweaker's newer version throws a lot more warnings and whatnot into the minetweaker log, instead of just saying it fails, so those first few warnings may be nothing.  The TiC Smeltery one worries me a little bit, but we may just have the ore dictionary wrong.  The last few with AOBD are just items that are now registered under PoorOres taking priority over AOBD's.

**Comment by UndeadZeratul** [comment]
Since we seem to still have issues with this, I'll take a look as soon as I can.

**Comment by UndeadZeratul** [comment]
I've gone ahead and revised the fixes made a month ago, let's see if these work...

**Comment by UndeadZeratul** [comment]
This time I only saw the warnings that recipes have been added, but no hard errors.  I don't think we can do much about the warnings, as that's just how ModTweaker works (sadly).  Since the errors seem to be gone, I'm going to close this.
